kumuluzee:
  name: questionnaire-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/QuestionnaireDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5433/questionnaire-data
      username: dbuser
      password: postgres
      pool:
        max-size: 5
    - jndi-name: jdbc/AnswerDataDS
      connection-url: jdbc:postgresql://0.0.0.0:5434/answer-data
      username: dbuser
      password: postgres
      pool:
        max-size: 5
  config:
    consul:
      agent: http://52.224.38.169:80
  health:
    checks:
      - data-source-health-check:
          type: liveness
          jndi-name: jdbc/QuestionnaireDataDS
      - data-source-health-check:
          type: liveness
          jndi-name: jdbc/AnswerDataDS
  metrics:
    web-instrumentation:
      - name: questionnaire-endpoint
        url-pattern: /v1/questionnaire
      - name: answers-endpoint
        url-pattern: /v1/answers
  streaming:
    kafka:
      producer:
        bootstrap-servers: rocket-01.srvs.cloudkafka.com:9094
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-256
        group-id: trips
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        session-timeout-ms: 30000
        sasl-jaas-config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="hus39ssl" password="h8UPiqVSJZzGlTpbXQ4Yl4vC2Y_Zi1Jo";'
rest-properties:
  config:
    broken: false
streaming-properties:
  processing-topic: hus39ssl-trips_processing
